'use strict';window.DOMHandler=class{constructor(e,a){this._iRuntime=e;this._componentId=a;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(e,a,b,c){this._iRuntime.PostToRuntimeComponent(this._componentId,e,a,b,c)}PostToRuntimeAsync(e,a,b,c){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,e,a,b,c)}_PostToRuntimeMaybeSync(e,a,b){this._iRuntime.UsesWorker()?this.PostToRuntime(e,a,b):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:e,dispatchOpts:b||null,data:a,responseId:null})}AddRuntimeMessageHandler(e,a){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,e,a)}AddRuntimeMessageHandlers(e){for(const [a,b]of e)this.AddRuntimeMessageHandler(a,b)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(e,a){this._callback=e;this._interval=a;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(e){this._canRunImmediate=!!e}Call(){if(-1===this._timerId){var e=Date.now(),a=e-this._lastCallTime,b=this._interval;a>=b&&this._canRunImmediate?(this._lastCallTime=e,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(b-a,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(e,a){super(e,a);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",b=>this._OnCreate(b)],["destroy",b=>this._OnDestroy(b)],["set-visible",b=>this._OnSetVisible(b)],["update-position",b=>this._OnUpdatePosition(b)],["update-state",b=>this._OnUpdateState(b)],["focus",b=>this._OnSetFocus(b)],["set-css-style",b=>this._OnSetCssStyle(b)],["set-attribute",b=>this._OnSetAttribute(b)],["remove-attribute",
b=>this._OnRemoveAttribute(b)]]);this.AddDOMElementMessageHandler("get-element",b=>b)}SetAutoAttach(e){this._autoAttach=!!e}AddDOMElementMessageHandler(e,a){this.AddRuntimeMessageHandler(e,b=>{const c=this._elementMap.get(b.elementId);return a(c,b)})}_OnCreate(e){const a=e.elementId,b=this.CreateElement(a,e);this._elementMap.set(a,b);b.style.boxSizing="border-box";e.isVisible||(b.style.display="none");e=this._GetFocusElement(b);e.addEventListener("focus",c=>this._OnFocus(a));e.addEventListener("blur",
c=>this._OnBlur(a));this._autoAttach&&document.body.appendChild(b)}CreateElement(e,a){throw Error("required override");}DestroyElement(e){}_OnDestroy(e){e=e.elementId;const a=this._elementMap.get(e);this.DestroyElement(a);this._autoAttach&&a.parentElement.removeChild(a);this._elementMap.delete(e)}PostToRuntimeElement(e,a,b){b||(b={});b.elementId=a;this.PostToRuntime(e,b)}_PostToRuntimeElementMaybeSync(e,a,b){b||(b={});b.elementId=a;this._PostToRuntimeMaybeSync(e,b)}_OnSetVisible(e){this._autoAttach&&
(this._elementMap.get(e.elementId).style.display=e.isVisible?"":"none")}_OnUpdatePosition(e){if(this._autoAttach){var a=this._elementMap.get(e.elementId);a.style.left=e.left+"px";a.style.top=e.top+"px";a.style.width=e.width+"px";a.style.height=e.height+"px";e=e.fontSize;null!==e&&(a.style.fontSize=e+"em")}}_OnUpdateState(e){const a=this._elementMap.get(e.elementId);this.UpdateState(a,e)}UpdateState(e,a){throw Error("required override");}_GetFocusElement(e){return e}_OnFocus(e){this.PostToRuntimeElement("elem-focused",
e)}_OnBlur(e){this.PostToRuntimeElement("elem-blurred",e)}_OnSetFocus(e){const a=this._GetFocusElement(this._elementMap.get(e.elementId));e.focus?a.focus():a.blur()}_OnSetCssStyle(e){this._elementMap.get(e.elementId).style[e.prop]=e.val}_OnSetAttribute(e){this._elementMap.get(e.elementId).setAttribute(e.name,e.val)}_OnRemoveAttribute(e){this._elementMap.get(e.elementId).removeAttribute(e.name)}GetElementById(e){return this._elementMap.get(e)}};"use strict";
{const e=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),a=/android/i.test(navigator.userAgent);let b=0;function c(g){const d=document.createElement("script");d.async=!1;d.type="module";return g.isStringSrc?new Promise(k=>{const l="c3_resolve_"+b;++b;self[l]=k;d.textContent=g.str+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=g;document.head.appendChild(d)})}let h=!1,m=!1;function p(){if(!h){try{new Worker("blob://",{get type(){m=
!0}})}catch(g){}h=!0}return m}let u=new Audio;const v={"audio/webm; codecs=opus":!!u.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!u.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!u.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!u.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!u.canPlayType("audio/mp4"),"audio/mpeg":!!u.canPlayType("audio/mpeg")};u=null;async function B(g){g=await w(g);return(new TextDecoder("utf-8")).decode(g)}
function w(g){return new Promise((d,k)=>{const l=new FileReader;l.onload=n=>d(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(g)})}const x=[];let A=0;window.RealFile=window.File;const C=[],F=new Map,z=new Map;let G=0;const D=[];self.runOnStartup=function(g){if("function"!==typeof g)throw Error("runOnStartup called without a function");D.push(g)};const I=new Set(["cordova","playable-ad","instant-games"]);function H(g){return I.has(g)}let f=!1;window.RuntimeInterface=class g{constructor(d){this._useWorker=
d.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=d.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=d.exportType;this._isFileProtocol="file"===location.protocol.substr(0,4);!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&p()||(this._useWorker=
!1);if("playable-ad"===this._exportType||"instant-games"===this._exportType)this._useWorker=!1;if("cordova"===this._exportType&&this._useWorker)if(a){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],10)||(this._useWorker=!1)}else this._useWorker=!1;this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||!this._isFileProtocol||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
"html5"!==this._exportType||window.isSecureContext||console.warn("[Construct 3] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",k=>this._OnCordovaFetchLocalFile(k));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",k=>this._OnCreateJobWorker(k));"cordova"===this._exportType?document.addEventListener("deviceready",
()=>this._Init(d)):this._Init(d)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsFileProtocol(){return this._isFileProtocol}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return e&&
"cordova"===this._exportType}IsiOSWebView(){const d=navigator.userAgent;return e&&H(this._exportType)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}IsAndroid(){return a}IsAndroidWebView(){return a&&H(this._exportType)}async _Init(d){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let l=0,n=d.engineScripts.length;l<
n;++l){var k=d.engineScripts[l].toLowerCase();this._localFileStrings.hasOwnProperty(k)?d.engineScripts[l]={isStringSrc:!0,str:this._localFileStrings[k]}:this._localFileBlobs.hasOwnProperty(k)&&(d.engineScripts[l]=URL.createObjectURL(this._localFileBlobs[k]))}}d.baseUrl?this._baseUrl=d.baseUrl:(k=location.origin,this._baseUrl=("null"===k?"file:///":k)+location.pathname,k=this._baseUrl.lastIndexOf("/"),-1!==k&&(this._baseUrl=this._baseUrl.substr(0,k+1)));d.workerScripts&&(this._workerScriptURLs=d.workerScripts);
k=new MessageChannel;this._messageChannelPort=k.port1;this._messageChannelPort.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this._OnMessageFromDebugger(l));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(d,k.port2):
await this._InitDOM(d,k.port2)}_GetWorkerURL(d){d=this._workerScriptURLs.hasOwnProperty(d)?this._workerScriptURLs[d]:d.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(d.toLowerCase())?this._localFileBlobs[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async CreateWorker(d,k,l){if(d.startsWith("blob:"))return new Worker(d,l);if("cordova"===
this._exportType&&this._isFileProtocol)return d=await this.CordovaFetchLocalFileAsArrayBuffer(l.isC3MainWorker?d:this._scriptFolder+d),d=new Blob([d],{type:"application/javascript"}),new Worker(URL.createObjectURL(d),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,
1)}_GetCommonRuntimeOptions(d){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,isFullscreen:g.IsDocumentFullscreen(),projectData:d.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:d.exportType,isDebug:-1<
self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:v,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isFileProtocol:this._isFileProtocol,isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(d,k){var l=this._GetWorkerURL(d.workerMainUrl);
this._worker=await this.CreateWorker(l,this._baseUrl,{type:"module",name:"Runtime",isC3MainWorker:!0});this._canvas=document.createElement("canvas");this._canvas.style.display="none";l=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;let n=d.workerDependencyScripts||[],r=d.engineScripts;n=await Promise.all(n.map(q=>this._MaybeGetCordovaScriptURL(q)));r=await Promise.all(r.map(q=>this._MaybeGetCordovaScriptURL(q)));if("cordova"===this._exportType)for(let q=
0,t=d.projectScripts.length;q<t;++q){const y=d.projectScripts[q],E=y[0];if(E===d.mainProjectScript||"scriptsInEvents.js"===E||E.endsWith("/scriptsInEvents.js"))y[1]=await this._MaybeGetCordovaScriptURL(E)}this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:n,engineScripts:r,projectScripts:d.projectScripts,mainProjectScript:d.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,
l,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=C.map(q=>new q(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(q,t)=>this._runtimeDomHandler._InvokeFunctionFromJS(q,t);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(d,k){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=
C.map(q=>new q(this));this._FindRuntimeDOMHandler();var l=d.engineScripts.map(q=>"string"===typeof q?(new URL(q,this._baseUrl)).toString():q);Array.isArray(d.workerDependencyScripts)&&l.unshift(...d.workerDependencyScripts);l=await Promise.all(l.map(q=>this._MaybeGetCordovaScriptURL(q)));await Promise.all(l.map(q=>c(q)));l=self.C3_ProjectScriptsStatus;const n=d.mainProjectScript,r=d.projectScripts;for(let [q,t]of r)if(t||(t=q),q===n)try{t=await this._MaybeGetCordovaScriptURL(t),await c(t),"preview"!==
this._exportType||l[q]||this._ReportProjectMainScriptError(q,"main script did not run to completion")}catch(y){this._ReportProjectMainScriptError(q,y)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))t=await this._MaybeGetCordovaScriptURL(t),await c(t);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(d=Object.assign(this._GetCommonRuntimeOptions(d),{isInWorker:!1,messagePort:k,canvas:this._canvas,runOnStartupFunctions:D}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this._localRuntime,d))}_ReportProjectMainScriptError(d,k){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const d=
window.cr_previewLoadingElem;d&&(d.parentElement.removeChild(d),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(d){d=await this._jobScheduler._CreateJobWorker();return{outputPort:d,transferables:[d]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(d,k,l,n,r){this._messageChannelPort.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:null},r)}PostToRuntimeComponentAsync(d,
k,l,n,r){const q=G++,t=new Promise((y,E)=>{z.set(q,{resolve:y,reject:E})});this._messageChannelPort.postMessage({type:"event",component:d,handler:k,dispatchOpts:n||null,data:l,responseId:q},r);return t}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this._OnEventFromRuntime(d);if("result"===k)this._OnResultFromRuntime(d);else if("runtime-ready"===k)this._OnRuntimeReady();else if("alert-error"===k)this._RemoveLoadingMessage(),alert(d.message);else if("creating-runtime"===k)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${k}'`);}_OnEventFromRuntime(d){const k=d.component,l=d.handler,n=d.data,r=d.responseId;if(d=F.get(k))if(d=d.get(l)){var q=null;try{q=d(n)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==r&&this._PostResultToRuntime(r,!1,""+t);return}if(null===r)return q;q&&q.then?q.then(t=>this._PostResultToRuntime(r,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this._PostResultToRuntime(r,!1,""+t)}):this._PostResultToRuntime(r,
!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}_PostResultToRuntime(d,k,l){let n;l&&l.transferables&&(n=l.transferables);this._messageChannelPort.postMessage({type:"result",responseId:d,isOk:k,result:l},n)}_OnResultFromRuntime(d){const k=d.responseId,l=d.isOk;d=d.result;const n=z.get(k);l?n.resolve(d):n.reject(d);z.delete(k)}AddRuntimeComponentMessageHandler(d,k,l){let n=F.get(d);n||(n=new Map,F.set(d,n));if(n.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);
n.set(k,l)}static AddDOMHandlerClass(d){if(C.includes(d))throw Error("DOM handler already added");C.push(d)}_FindRuntimeDOMHandler(){for(const d of this._domHandlers)if("runtime"===d.GetComponentID()){this._runtimeDomHandler=d;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(d){this.PostToRuntimeComponent("debugger","message",d)}_OnRuntimeReady(){for(const d of this._domHandlers)d.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||f)}static _SetWrapperIsFullscreenFlag(d){f=!!d}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(d){this._rafCallbacks.push(d);this._RequestAnimationFrame()}_RemoveRAFCallback(d){d=this._rafCallbacks.indexOf(d);if(-1===d)throw Error("invalid callback");this._rafCallbacks.splice(d,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const d of this._rafCallbacks)d();this._RequestAnimationFrame()}TryPlayMedia(d){this._runtimeDomHandler.TryPlayMedia(d)}RemovePendingPlay(d){this._runtimeDomHandler.RemovePendingPlay(d)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(d){this._runtimeDomHandler.SetSilent(d)}IsAudioFormatSupported(d){return!!v[d]}async _WasmDecodeWebMOpus(d){d=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}IsAbsoluteURL(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}IsRelativeURL(d){return!this.IsAbsoluteURL(d)}async _MaybeGetCordovaScriptURL(d){return"cordova"===this._exportType&&(d.startsWith("file:")||this._isFileProtocol&&this.IsRelativeURL(d))?(d.startsWith(this._baseUrl)&&(d=d.substr(this._baseUrl.length)),d=await this.CordovaFetchLocalFileAsArrayBuffer(d),
d=new Blob([d],{type:"application/javascript"}),URL.createObjectURL(d)):d}async _OnCordovaFetchLocalFile(d){const k=d.filename;switch(d.as){case "text":return await this.CordovaFetchLocalFileAsText(k);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(k);default:throw Error("unsupported type");}}_GetPermissionAPI(){const d=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof d)throw Error("Permission API is not loaded");return d}_MapPermissionID(d,
k){d=d[k];if("string"!==typeof d)throw Error("Invalid permission name");return d}_HasPermission(d){const k=this._GetPermissionAPI();return new Promise((l,n)=>k.checkPermission(this._MapPermissionID(k,d),r=>l(!!r.hasPermission),n))}_RequestPermission(d){const k=this._GetPermissionAPI();return new Promise((l,n)=>k.requestPermission(this._MapPermissionID(k,d),r=>l(!!r.hasPermission),n))}async RequestPermissions(d){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const k of d)if(!await this._HasPermission(k)&&
!1===await this._RequestPermission(k))return!1;return!0}async RequirePermissions(...d){if(!1===await this.RequestPermissions(d))throw Error("Permission not granted");}CordovaFetchLocalFile(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,r=>{r.file(l,n)},n)})}async CordovaFetchLocalFileAsText(d){d=await this.CordovaFetchLocalFile(d);return await B(d)}_CordovaMaybeStartNextArrayBufferRead(){if(x.length&&!(8<=A)){A++;
var d=x.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(d.filename,d.successCallback,d.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(d){return new Promise((k,l)=>{x.push({filename:d,successCallback:n=>{A--;this._CordovaMaybeStartNextArrayBufferRead();k(n)},errorCallback:n=>{A--;this._CordovaMaybeStartNextArrayBufferRead();l(n)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(d,k,l){try{const n=await this.CordovaFetchLocalFile(d),r=await w(n);
k(r)}catch(n){l(n)}}_SendWrapperMessage(d){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async _ConvertDataUrisToBlobs(){const d=[];for(const [k,l]of Object.entries(this._localFileBlobs))d.push(this._ConvertDataUriToBlobs(k,l));await Promise.all(d)}async _ConvertDataUriToBlobs(d,k){if("object"===
typeof k)this._localFileBlobs[d]=new Blob([k.str],{type:k.type}),this._localFileStrings[d]=k.str;else{let l=await this._FetchDataUri(k);l||(l=this._DataURIToBinaryBlobSync(k));this._localFileBlobs[d]=l}}async _FetchDataUri(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}_DataURIToBinaryBlobSync(d){d=
this._ParseDataURI(d);return this._BinaryStringToBlob(d.data,d.mime_type)}_ParseDataURI(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(5,k);d=d.substring(k+1);k=l.split(";");l=k[0]||"";const n=k[2];d="base64"===k[1]||"base64"===n?atob(d):decodeURIComponent(d);return{mime_type:l,data:d}}_BinaryStringToBlob(d,k){var l=d.length;let n=l>>2,r=new Uint8Array(l),q=new Uint32Array(r.buffer,0,n),t,y;for(y=t=0;t<n;++t)q[t]=d.charCodeAt(y++)|d.charCodeAt(y++)<<
8|d.charCodeAt(y++)<<16|d.charCodeAt(y++)<<24;for(l&=3;l--;)r[y]=d.charCodeAt(y),++y;return new Blob([r],{type:k})}}}"use strict";
{const e=self.RuntimeInterface;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},h={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((g,d)=>{const k=document.createElement("link");k.onload=()=>g(k);k.onerror=
l=>d(l);k.rel="stylesheet";k.href=f;document.head.appendChild(k)})}function u(f){return new Promise((g,d)=>{const k=new Image;k.onload=()=>g(k);k.onerror=l=>d(l);k.src=f})}async function v(f){f=URL.createObjectURL(f);try{return await u(f)}finally{URL.revokeObjectURL(f)}}function B(f){return new Promise((g,d)=>{let k=new FileReader;k.onload=l=>g(l.target.result);k.onerror=l=>d(l);k.readAsText(f)})}async function w(f,g,d){if(!/firefox/i.test(navigator.userAgent))return await v(f);var k=await B(f);k=
(new DOMParser).parseFromString(k,"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),r=l.getAttribute("height");if(!n.includes("%")&&!r.includes("%"))return await v(f)}l.setAttribute("width",g+"px");l.setAttribute("height",d+"px");k=(new XMLSerializer).serializeToString(k);f=new Blob([k],{type:"image/svg+xml"});return await v(f)}function x(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);
return!1}const A=new Set(["input","textarea","datalist","select"]);function C(f){return A.has(f.tagName.toLowerCase())||x(f)}const F=new Set(["canvas","body","html"]);function z(f){const g=f.target.tagName.toLowerCase();F.has(g)&&f.preventDefault()}function G(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await v(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";
document.body.appendChild(f);const g=f.getBoundingClientRect();document.body.removeChild(f);return[g.width,g.height]}};self.C3_RasterSvgImageBlob=async function(f,g,d,k,l){f=await w(f,g,d);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(f,0,0,g,d);return n};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function I(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}function H(){const f=
document.activeElement;if(!f)return!1;const g=f.tagName.toLowerCase(),d=new Set("email number password search tel text url".split(" "));return"textarea"===g?!0:"input"===g?d.has(f.type.toLowerCase()||"text"):x(f)}e.AddDOMHandlerClass(class extends self.DOMHandler{constructor(f){super(f,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=
this._debugHighlightElem=null;this._pointerRawMovementY=this._pointerRawMovementX=0;this._lastWindowWidth=f._GetWindowInnerWidth();this._lastWindowHeight=f._GetWindowInnerHeight();this._virtualKeyboardHeight=0;f.AddRuntimeComponentMessageHandler("canvas","update-size",k=>this._OnUpdateCanvasSize(k));f.AddRuntimeComponentMessageHandler("runtime","invoke-download",k=>this._OnInvokeDownload(k));f.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",k=>this._OnRasterSvgImage(k));f.AddRuntimeComponentMessageHandler("runtime",
"get-svg-image-size",k=>this._OnGetSvgImageSize(k));f.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",k=>this._OnSetTargetOrientation(k));f.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());f.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",k=>this._OnPostToDebugger(k));f.AddRuntimeComponentMessageHandler("runtime","go-to-script",k=>this._OnPostToDebugger(k));f.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>
this._OnBeforeStartTicking());f.AddRuntimeComponentMessageHandler("runtime","debug-highlight",k=>this._OnDebugHighlight(k));f.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());f.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());f.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",k=>this._OnAddStylesheet(k));f.AddRuntimeComponentMessageHandler("runtime","alert",k=>this._OnAlert(k));
f.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target,n=l.tagName.toLowerCase();g.has(n)||x(l)||k.preventDefault()});const d=f.GetCanvas();window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);d.addEventListener("selectstart",z);d.addEventListener("gesturehold",z);window.addEventListener("touchstart",z,{passive:!1});
"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),d.addEventListener("pointerdown",z)):d.addEventListener("touchstart",z);this._mousePointerLastButtons=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",k=>this._OnFullscreenError(k));window.addEventListener("webkitfullscreenerror",k=>this._OnFullscreenError(k));window.addEventListener("mozfullscreenerror",k=>this._OnFullscreenError(k));f.IsiOSWebView()&&window.addEventListener("focusout",()=>{H()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=
k=>this._OnWrapperMessage(k);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}Attach(){window.addEventListener("focus",
()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:I()});this._mousePointerLastButtons=0});window.addEventListener("focusin",g=>{C(g.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",g=>this._OnKeyEvent("keydown",g));window.addEventListener("keyup",g=>this._OnKeyEvent("keyup",g));window.addEventListener("dblclick",g=>this._OnMouseEvent("dblclick",g,c));window.addEventListener("wheel",
g=>this._OnMouseWheelEvent("wheel",g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",g=>{this._HandlePointerDownFocus(g);this._OnPointerEvent("pointerdown",g)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",g=>this._OnPointerRawUpdate(g))):
window.addEventListener("pointermove",g=>this._OnPointerEvent("pointermove",g)),window.addEventListener("pointerup",g=>this._OnPointerEvent("pointerup",g)),window.addEventListener("pointercancel",g=>this._OnPointerEvent("pointercancel",g))):(window.addEventListener("mousedown",g=>{this._HandlePointerDownFocus(g);this._OnMouseEventAsPointer("pointerdown",g)}),window.addEventListener("mousemove",g=>this._OnMouseEventAsPointer("pointermove",g)),window.addEventListener("mouseup",g=>this._OnMouseEventAsPointer("pointerup",
g)),window.addEventListener("touchstart",g=>{this._HandlePointerDownFocus(g);this._OnTouchEvent("pointerdown",g)}),window.addEventListener("touchmove",g=>this._OnTouchEvent("pointermove",g)),window.addEventListener("touchend",g=>this._OnTouchEvent("pointerup",g)),window.addEventListener("touchcancel",g=>this._OnTouchEvent("pointercancel",g)));const f=()=>this._PlayPendingMedia();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",f,!0);window.addEventListener("click",f,!0);
window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0);this._iRuntime.IsAndroid()&&!this._iRuntime.IsAndroidWebView()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{this._OnAndroidVirtualKeyboardChange(this._GetWindowInnerHeight(),navigator.virtualKeyboard.boundingRect.height)}))}_OnAndroidVirtualKeyboardChange(f,g){document.body.style.transform="";if(0<g){var d=document.activeElement;
d&&(d=d.getBoundingClientRect(),f=(d.top+d.bottom)/2-(f-g)/2,f>g&&(f=g),0>f&&(f=0),0<f&&(document.body.style.transform=`translateY(${-f}px)`))}}_PostRuntimeEvent(f,g){this.PostToRuntime(f,g||null,m)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const f=this._GetWindowInnerWidth(),g=this._GetWindowInnerHeight();if(this._iRuntime.IsAndroidWebView()){if(this._lastWindowWidth===f&&g<this._lastWindowHeight){this._virtualKeyboardHeight=
this._lastWindowHeight-g;this._OnAndroidVirtualKeyboardChange(this._lastWindowHeight,this._virtualKeyboardHeight);return}0<this._virtualKeyboardHeight&&(this._virtualKeyboardHeight=0,this._OnAndroidVirtualKeyboardChange(g,this._virtualKeyboardHeight));this._lastWindowWidth=f;this._lastWindowHeight=g}this._PostRuntimeEvent("window-resize",{innerWidth:f,innerHeight:g,devicePixelRatio:window.devicePixelRatio,isFullscreen:e.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&
clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(f,g,0))}_ScheduleSimulatedResize(f,g,d){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(f,g,d),48)}_OnSimulatedResize(f,g,d){const k=this._GetWindowInnerWidth(),l=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;k!=f||l!=g?this._PostRuntimeEvent("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,
isFullscreen:e.IsDocumentFullscreen()}):10>d&&this._ScheduleSimulatedResize(k,l,d+1)}_OnSetTargetOrientation(f){this._targetOrientation=f.targetOrientation}_TrySetTargetOrientation(){const f=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(f):screen.webkitLockOrientation?g=screen.webkitLockOrientation(f):screen.mozLockOrientation?
g=screen.mozLockOrientation(f):screen.msLockOrientation&&(g=screen.msLockOrientation(f));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}_OnFullscreenChange(){const f=e.IsDocumentFullscreen();f&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:f,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(f){console.warn("[Construct 3] Fullscreen request failed: ",
f);this.PostToRuntime("fullscreenerror",{isFullscreen:e.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(f){f?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:f})}_OnKeyEvent(f,g){"Backspace"===g.key&&z(g);const d=b.get(g.code)||g.code;this._PostToRuntimeMaybeSync(f,{code:d,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,
metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},c)}_OnMouseWheelEvent(f,g){this.PostToRuntime(f,{clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,deltaX:g.deltaX,deltaY:g.deltaY,deltaZ:g.deltaZ,deltaMode:g.deltaMode,timeStamp:g.timeStamp},c)}_OnMouseEvent(f,g,d){a(g)||this._PostToRuntimeMaybeSync(f,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,timeStamp:g.timeStamp},d)}_OnMouseEventAsPointer(f,
g){if(!a(g)){var d=this._mousePointerLastButtons;"pointerdown"===f&&0!==d?f="pointermove":"pointerup"===f&&0!==g.buttons&&(f="pointermove");this._PostToRuntimeMaybeSync(f,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:d,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},c);this._mousePointerLastButtons=g.buttons;
this._OnMouseEvent(g.type,g,h)}}_OnPointerEvent(f,g){this._pointerRawUpdateRateLimiter&&"pointermove"!==f&&this._pointerRawUpdateRateLimiter.Reset();var d=0;"mouse"===g.pointerType&&(d=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(f,{pointerId:g.pointerId,pointerType:g.pointerType,button:g.button,buttons:g.buttons,lastButtons:d,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,movementX:(g.movementX||0)+this._pointerRawMovementX,movementY:(g.movementY||0)+this._pointerRawMovementY,
width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},c);this._pointerRawMovementY=this._pointerRawMovementX=0;"mouse"===g.pointerType&&(d="mousemove","pointerdown"===f?d="mousedown":"pointerup"===f&&(d="mouseup"),this._OnMouseEvent(d,g,h),this._mousePointerLastButtons=g.buttons)}_OnPointerRawUpdate(f){this._lastPointerRawUpdateEvent&&(this._pointerRawMovementX+=this._lastPointerRawUpdateEvent.movementX||
0,this._pointerRawMovementY+=this._lastPointerRawUpdateEvent.movementY||0);this._lastPointerRawUpdateEvent=f;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(f,g){for(let d=0,k=g.changedTouches.length;d<k;++d){const l=g.changedTouches[d];this._PostToRuntimeMaybeSync(f,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,
clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,movementX:g.movementX||0,movementY:g.movementY||0,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:g.timeStamp},c)}}_HandlePointerDownFocus(f){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(f.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(f){return!f||
f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",f=>this._OnDeviceOrientation(f)),window.addEventListener("deviceorientationabsolute",f=>this._OnDeviceOrientationAbsolute(f)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",f=>this._OnDeviceMotion(f)))}_OnDeviceOrientation(f){this.PostToRuntime("deviceorientation",
{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},c)}_OnDeviceOrientationAbsolute(f){this.PostToRuntime("deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}_OnDeviceMotion(f){let g=null;var d=f.acceleration;d&&(g={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var k=f.accelerationIncludingGravity;k&&(d=
{x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=f.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});this.PostToRuntime("devicemotion",{acceleration:g,accelerationIncludingGravity:d,rotationRate:k,interval:f.interval,timeStamp:f.timeStamp},c)}_OnUpdateCanvasSize(f){const g=this.GetRuntimeInterface().GetCanvas();g.style.width=f.styleWidth+"px";g.style.height=f.styleHeight+"px";g.style.marginLeft=f.marginLeft+"px";g.style.marginTop=f.marginTop+"px";this._isFirstSizeUpdate&&(g.style.display=
"",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(f){const g=f.url;f=f.filename;const d=document.createElement("a"),k=document.body;d.textContent=f;d.href=g;d.download=f;k.appendChild(d);d.click();k.removeChild(d)}async _OnRasterSvgImage(f){var g=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);g=g?await createImageBitmap(f,g):await createImageBitmap(f);return{imageBitmap:g,transferables:[g]}}async _OnGetSvgImageSize(f){return await self.C3_GetSvgImageSize(f.blob)}async _OnAddStylesheet(f){await p(f.url)}_PlayPendingMedia(){var f=
[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const g of f)(f=g.play())&&f.catch(d=>{this._mediaRemovedPendingPlay.has(g)||this._mediaPendingPlay.add(g)})}TryPlayMedia(f){if("function"!==typeof f.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(f);let g;try{g=f.play()}catch(d){this._mediaPendingPlay.add(f);return}g&&g.catch(d=>{this._mediaRemovedPendingPlay.has(f)||this._mediaPendingPlay.add(f)})}RemovePendingPlay(f){this._mediaPendingPlay.delete(f);
this._mediaRemovedPendingPlay.add(f)}SetSilent(f){this._isSilent=!!f}_OnHideCordovaSplash(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(f){if(f.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var g=this._debugHighlightElem;g.style.display="";g.style.left=f.left-1+"px";g.style.top=f.top-1+"px";g.style.width=
f.width+2+"px";g.style.height=f.height+2+"px";g.textContent=f.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}_InvokeFunctionFromJS(f,g){return this.PostToRuntimeAsync("js-invoke-function",{name:f,params:g})}_OnAlert(f){alert(f.message)}_OnWrapperMessage(f){"entered-fullscreen"===f?(e._SetWrapperIsFullscreenFlag(!0),
this._OnFullscreenChange()):"exited-fullscreen"===f?(e._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",f)}})}"use strict";
self.JobSchedulerDOM=class{constructor(e){this._runtimeInterface=e;this._baseUrl=e.GetBaseURL();"preview"===e.GetExportType()?this._baseUrl+="workers/":this._baseUrl+=e.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var e=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"DispatchWorker"});e=new MessageChannel;this._inputPort=e.port1;this._dispatchWorker.postMessage({type:"_init","in-port":e.port2},[e.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const e=this._jobWorkers.length;var a=this._runtimeInterface._GetWorkerURL("jobworker.js");a=await this._runtimeInterface.CreateWorker(a,this._baseUrl,{name:"JobWorker"+e});const b=new MessageChannel,c=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:b.port1},[b.port1]);a.postMessage({type:"init",number:e,"dispatch-port":b.port2,"output-port":c.port2},[b.port2,c.port2]);this._jobWorkers.push(a);return c.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(e){super(e,"mouse");this.AddRuntimeMessageHandlers([["cursor",a=>this._OnChangeCursorStyle(a)],["request-pointer-lock",()=>this._OnRequestPointerLock()],["release-pointer-lock",()=>this._OnReleasePointerLock()]]);document.addEventListener("pointerlockchange",a=>this._OnPointerLockChange());document.addEventListener("pointerlockerror",a=>this._OnPointerLockError())}_OnChangeCursorStyle(e){document.documentElement.style.cursor=
e}_OnRequestPointerLock(){this._iRuntime.GetCanvas().requestPointerLock()}_OnReleasePointerLock(){document.exitPointerLock()}_OnPointerLockChange(){this.PostToRuntime("pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})}_OnPointerLockError(){this.PostToRuntime("pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})}});"use strict";
{const e=180/Math.PI;self.AudioDOMHandler=class extends self.DOMHandler{constructor(a){super(a,"audio");this._destinationNode=this._audioContext=null;this._hasAttachedUnblockEvents=this._hasUnblocked=!1;this._unblockFunc=()=>this._UnblockAudioContext();this._audioBuffers=[];this._audioInstances=[];this._lastAudioInstance=null;this._lastPlayedTag="";this._lastTickCount=-1;this._pendingTags=new Map;this._masterVolume=1;this._isSilent=!1;this._timeScaleMode=0;this._timeScale=1;this._gameTime=0;this._panningModel=
"HRTF";this._distanceModel="inverse";this._refDistance=600;this._maxDistance=1E4;this._rolloffFactor=1;this._hasAnySoftwareDecodedMusic=this._playMusicAsSound=!1;this._supportsWebMOpus=this._iRuntime.IsAudioFormatSupported("audio/webm; codecs=opus");this._effects=new Map;this._analysers=new Set;this._isPendingPostFxState=!1;this._microphoneTag="";this._microphoneSource=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this._OnMicrophoneStream(b,c);this._destMediaStreamNode=null;self.C3Audio_GetOutputStream=
()=>this._OnGetOutputStream();self.C3Audio_DOMInterface=this;this.AddRuntimeMessageHandlers([["create-audio-context",b=>this._CreateAudioContext(b)],["play",b=>this._Play(b)],["stop",b=>this._Stop(b)],["stop-all",()=>this._StopAll()],["set-paused",b=>this._SetPaused(b)],["set-volume",b=>this._SetVolume(b)],["fade-volume",b=>this._FadeVolume(b)],["set-master-volume",b=>this._SetMasterVolume(b)],["set-muted",b=>this._SetMuted(b)],["set-silent",b=>this._SetSilent(b)],["set-looping",b=>this._SetLooping(b)],
["set-playback-rate",b=>this._SetPlaybackRate(b)],["seek",b=>this._Seek(b)],["preload",b=>this._Preload(b)],["unload",b=>this._Unload(b)],["unload-all",()=>this._UnloadAll()],["set-suspended",b=>this._SetSuspended(b)],["get-suspended",b=>this._GetSuspended(b)],["add-effect",b=>this._AddEffect(b)],["set-effect-param",b=>this._SetEffectParam(b)],["remove-effects",b=>this._RemoveEffects(b)],["tick",b=>this._OnTick(b)],["load-state",b=>this._OnLoadState(b)]])}async _CreateAudioContext(a){a.isiOSCordova&&
(this._playMusicAsSound=!0);this._timeScaleMode=a.timeScaleMode;this._panningModel=["equalpower","HRTF","soundfield"][a.panningModel];this._distanceModel=["linear","inverse","exponential"][a.distanceModel];this._refDistance=a.refDistance;this._maxDistance=a.maxDistance;this._rolloffFactor=a.rolloffFactor;var b={latencyHint:a.latencyHint};this.SupportsWebMOpus()||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this._audioContext=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this._audioContext=
new webkitAudioContext(b);else throw Error("Web Audio API not supported");this._AttachUnblockEvents();this._audioContext.onstatechange=()=>{"running"!==this._audioContext.state&&this._AttachUnblockEvents()};this._destinationNode=this._audioContext.createGain();this._destinationNode.connect(this._audioContext.destination);b=a.listenerPos;this._audioContext.listener.setPosition(b[0],b[1],b[2]);this._audioContext.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.GetAudioCurrentTime();
try{await Promise.all(a.preloadList.map(c=>this._GetAudioBuffer(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this._audioContext.sampleRate}}_AttachUnblockEvents(){this._hasAttachedUnblockEvents||(this._hasUnblocked=!1,window.addEventListener("pointerup",this._unblockFunc,!0),window.addEventListener("touchend",this._unblockFunc,!0),window.addEventListener("click",this._unblockFunc,!0),window.addEventListener("keydown",this._unblockFunc,
!0),this._hasAttachedUnblockEvents=!0)}_DetachUnblockEvents(){this._hasAttachedUnblockEvents&&(this._hasUnblocked=!0,window.removeEventListener("pointerup",this._unblockFunc,!0),window.removeEventListener("touchend",this._unblockFunc,!0),window.removeEventListener("click",this._unblockFunc,!0),window.removeEventListener("keydown",this._unblockFunc,!0),this._hasAttachedUnblockEvents=!1)}_UnblockAudioContext(){if(!this._hasUnblocked){var a=this._audioContext;"suspended"===a.state&&a.resume&&a.resume();
var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this._DetachUnblockEvents()}}GetAudioContext(){return this._audioContext}GetAudioCurrentTime(){return this._audioContext.currentTime}GetDestinationNode(){return this._destinationNode}GetDestinationForTag(a){return(a=this._effects.get(a.toLowerCase()))?a[0].GetInputNode():this.GetDestinationNode()}AddEffectForTag(a,b){a=a.toLowerCase();let c=this._effects.get(a);c||(c=[],this._effects.set(a,
c));b._SetIndex(c.length);b._SetTag(a);c.push(b);this._ReconnectEffects(a)}_ReconnectEffects(a){let b=this.GetDestinationNode();const c=this._effects.get(a);if(c&&c.length){b=c[0].GetInputNode();for(let h=0,m=c.length;h<m;++h){const p=c[h];h+1===m?p.ConnectTo(this.GetDestinationNode()):p.ConnectTo(c[h+1].GetInputNode())}}for(const h of this.audioInstancesByTag(a))h.Reconnect(b);this._microphoneSource&&this._microphoneTag===a&&(this._microphoneSource.disconnect(),this._microphoneSource.connect(b))}GetMasterVolume(){return this._masterVolume}IsSilent(){return this._isSilent}GetTimeScaleMode(){return this._timeScaleMode}GetTimeScale(){return this._timeScale}GetGameTime(){return this._gameTime}IsPlayMusicAsSound(){return this._playMusicAsSound}SupportsWebMOpus(){return this._supportsWebMOpus}_SetHasAnySoftwareDecodedMusic(){this._hasAnySoftwareDecodedMusic=
!0}GetPanningModel(){return this._panningModel}GetDistanceModel(){return this._distanceModel}GetReferenceDistance(){return this._refDistance}GetMaxDistance(){return this._maxDistance}GetRolloffFactor(){return this._rolloffFactor}DecodeAudioData(a,b){return b?this._iRuntime._WasmDecodeWebMOpus(a).then(c=>{const h=this._audioContext.createBuffer(1,c.length,48E3);h.getChannelData(0).set(c);return h}):new Promise((c,h)=>{this._audioContext.decodeAudioData(a,c,h)})}TryPlayMedia(a){this._iRuntime.TryPlayMedia(a)}RemovePendingPlay(a){this._iRuntime.RemovePendingPlay(a)}ReleaseInstancesForBuffer(a){let b=
0;for(let c=0,h=this._audioInstances.length;c<h;++c){const m=this._audioInstances[c];this._audioInstances[b]=m;m.GetBuffer()===a?m.Release():++b}this._audioInstances.length=b}ReleaseAllMusicBuffers(){let a=0;for(let b=0,c=this._audioBuffers.length;b<c;++b){const h=this._audioBuffers[b];this._audioBuffers[a]=h;h.IsMusic()?h.Release():++a}this._audioBuffers.length=a}*audioInstancesByTag(a){if(a)for(const b of this._audioInstances)self.AudioDOMHandler.EqualsNoCase(b.GetTag(),a)&&(yield b);else this._lastAudioInstance&&
!this._lastAudioInstance.HasEnded()&&(yield this._lastAudioInstance)}async _GetAudioBuffer(a,b,c,h,m){for(const p of this._audioBuffers)if(p.GetUrl()===b)return await p.Load(),p;if(m)return null;h&&(this._playMusicAsSound||this._hasAnySoftwareDecodedMusic)&&this.ReleaseAllMusicBuffers();a=self.C3AudioBuffer.Create(this,a,b,c,h);this._audioBuffers.push(a);await a.Load();return a}async _GetAudioInstance(a,b,c,h,m){for(const p of this._audioInstances)if(p.GetUrl()===b&&(p.CanBeRecycled()||m))return p.SetTag(h),
p;a=(await this._GetAudioBuffer(a,b,c,m)).CreateInstance(h);this._audioInstances.push(a);return a}_AddPendingTag(a){let b=this._pendingTags.get(a);if(!b){let c=null;b={pendingCount:0,promise:new Promise(h=>c=h),resolve:c};this._pendingTags.set(a,b)}b.pendingCount++}_RemovePendingTag(a){const b=this._pendingTags.get(a);if(!b)throw Error("expected pending tag");b.pendingCount--;0===b.pendingCount&&(b.resolve(),this._pendingTags.delete(a))}TagReady(a){a||(a=this._lastPlayedTag);return(a=this._pendingTags.get(a))?
a.promise:Promise.resolve()}_MaybeStartTicking(){if(0<this._analysers.size)this._StartTicking();else for(const a of this._audioInstances)if(a.IsActive()){this._StartTicking();break}}Tick(){for(var a of this._analysers)a.Tick();a=this.GetAudioCurrentTime();for(var b of this._audioInstances)b.Tick(a);b=this._audioInstances.filter(c=>c.IsActive()).map(c=>c.GetState());this.PostToRuntime("state",{tickCount:this._lastTickCount,audioInstances:b,analysers:[...this._analysers].map(c=>c.GetData())});0===b.length&&
0===this._analysers.size&&this._StopTicking()}PostTrigger(a,b,c){this.PostToRuntime("trigger",{type:a,tag:b,aiid:c})}async _Play(a){const b=a.originalUrl,c=a.url,h=a.type,m=a.isMusic,p=a.tag,u=a.isLooping,v=a.vol,B=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this._audioContext.getOutputTimestamp?(a=this._audioContext.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this._audioContext.currentTime);this._lastPlayedTag=p;this._AddPendingTag(p);try{this._lastAudioInstance=
await this._GetAudioInstance(b,c,h,p,m),w?(this._lastAudioInstance.SetPannerEnabled(!0),this._lastAudioInstance.SetPan(w.x,w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this._lastAudioInstance.SetUID(w.uid)):this._lastAudioInstance.SetPannerEnabled(!1),this._lastAudioInstance.Play(u,v,B,x)}catch(A){console.error("[Construct 3] Audio: error starting playback: ",A);return}finally{this._RemovePendingTag(p)}this._StartTicking()}_Stop(a){a=a.tag;for(const b of this.audioInstancesByTag(a))b.Stop()}_StopAll(){for(const a of this._audioInstances)a.Stop()}_SetPaused(a){const b=
a.tag;a=a.paused;for(const c of this.audioInstancesByTag(b))a?c.Pause():c.Resume();this._MaybeStartTicking()}_SetVolume(a){const b=a.tag;a=a.vol;for(const c of this.audioInstancesByTag(b))c.SetVolume(a)}async _FadeVolume(a){const b=a.tag,c=a.vol,h=a.duration;a=a.stopOnEnd;await this.TagReady(b);for(const m of this.audioInstancesByTag(b))m.FadeVolume(c,h,a);this._MaybeStartTicking()}_SetMasterVolume(a){this._masterVolume=a.vol;for(const b of this._audioInstances)b._UpdateVolume()}_SetMuted(a){const b=
a.tag;a=a.isMuted;for(const c of this.audioInstancesByTag(b))c.SetMuted(a)}_SetSilent(a){this._isSilent=a.isSilent;this._iRuntime.SetSilent(this._isSilent);for(const b of this._audioInstances)b._UpdateMuted()}_SetLooping(a){const b=a.tag;a=a.isLooping;for(const c of this.audioInstancesByTag(b))c.SetLooping(a)}async _SetPlaybackRate(a){const b=a.tag;a=a.rate;await this.TagReady(b);for(const c of this.audioInstancesByTag(b))c.SetPlaybackRate(a)}async _Seek(a){const b=a.tag;a=a.pos;await this.TagReady(b);
for(const c of this.audioInstancesByTag(b))c.Seek(a)}async _Preload(a){const b=a.originalUrl,c=a.url,h=a.type;a=a.isMusic;try{await this._GetAudioInstance(b,c,h,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async _Unload(a){if(a=await this._GetAudioBuffer("",a.url,a.type,a.isMusic,!0))a.Release(),a=this._audioBuffers.indexOf(a),-1!==a&&this._audioBuffers.splice(a,1)}_UnloadAll(){for(const a of this._audioBuffers)a.Release();this._audioBuffers.length=0}_SetSuspended(a){a=
a.isSuspended;!a&&this._audioContext.resume&&this._audioContext.resume();for(const b of this._audioInstances)b.SetSuspended(a);a&&this._audioContext.suspend&&this._audioContext.suspend()}_GetSuspended(){return this._audioContext?this._audioContext.state:"suspended"}_OnTick(a){this._timeScale=a.timeScale;this._gameTime=a.gameTime;this._lastTickCount=a.tickCount;if(0!==this._timeScaleMode)for(var b of this._audioInstances)b._UpdatePlaybackRate();(b=a.listenerPos)&&this._audioContext.listener.setPosition(b[0],
b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const h of this._audioInstances)h.GetUID()===a&&h.SetPanXYA(c.x,c.y,c.angle)}}async _AddEffect(a){var b=a.type;const c=a.tag;var h=a.params;if("filter"===b)h=new self.C3AudioFilterFX(this,...h);else if("delay"===b)h=new self.C3AudioDelayFX(this,...h);else if("convolution"===b){b=null;try{b=await this._GetAudioBuffer(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",m);return}h=
new self.C3AudioConvolveFX(this,b.GetAudioBuffer(),...h);h._SetBufferInfo(a.bufferOriginalUrl,a.bufferUrl,a.bufferType)}else if("flanger"===b)h=new self.C3AudioFlangerFX(this,...h);else if("phaser"===b)h=new self.C3AudioPhaserFX(this,...h);else if("gain"===b)h=new self.C3AudioGainFX(this,...h);else if("tremolo"===b)h=new self.C3AudioTremoloFX(this,...h);else if("ringmod"===b)h=new self.C3AudioRingModFX(this,...h);else if("distortion"===b)h=new self.C3AudioDistortionFX(this,...h);else if("compressor"===
b)h=new self.C3AudioCompressorFX(this,...h);else if("analyser"===b)h=new self.C3AudioAnalyserFX(this,...h);else throw Error("invalid effect type");this.AddEffectForTag(c,h);this._PostUpdatedFxState()}_SetEffectParam(a){const b=a.index,c=a.param,h=a.value,m=a.ramp,p=a.time;a=this._effects.get(a.tag);!a||0>b||b>=a.length||(a[b].SetParam(c,h,m,p),this._PostUpdatedFxState())}_RemoveEffects(a){a=a.tag.toLowerCase();const b=this._effects.get(a);if(b&&b.length){for(const c of b)c.Release();this._effects.delete(a);
this._ReconnectEffects(a)}}_AddAnalyser(a){this._analysers.add(a);this._MaybeStartTicking()}_RemoveAnalyser(a){this._analysers.delete(a)}_PostUpdatedFxState(){this._isPendingPostFxState||(this._isPendingPostFxState=!0,Promise.resolve().then(()=>this._DoPostUpdatedFxState()))}_DoPostUpdatedFxState(){const a={};for(const [b,c]of this._effects)a[b]=c.map(h=>h.GetState());this.PostToRuntime("fxstate",{fxstate:a});this._isPendingPostFxState=!1}async _OnLoadState(a){const b=a.saveLoadMode;if(3!==b)for(var c of this._audioInstances)c.IsMusic()&&
1===b||(c.IsMusic()||2!==b)&&c.Stop();for(const h of this._effects.values())for(const m of h)m.Release();this._effects.clear();this._timeScale=a.timeScale;this._gameTime=a.gameTime;c=a.listenerPos;this._audioContext.listener.setPosition(c[0],c[1],c[2]);this._isSilent=a.isSilent;this._iRuntime.SetSilent(this._isSilent);this._masterVolume=a.masterVolume;c=[];for(const h of Object.values(a.effects))c.push(Promise.all(h.map(m=>this._AddEffect(m))));await Promise.all(c);await Promise.all(a.playing.map(h=>
this._LoadAudioInstance(h,b)));this._MaybeStartTicking()}async _LoadAudioInstance(a,b){if(3!==b){var c=a.bufferOriginalUrl,h=a.bufferUrl,m=a.bufferType,p=a.isMusic,u=a.tag,v=a.isLooping,B=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this._GetAudioInstance(c,h,m,u,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.LoadPanState(a.pan);b.Play(v,B,w,0);a.isPlaying||b.Pause();b._LoadAdditionalState(a)}}}_OnMicrophoneStream(a,b){this._microphoneSource&&
this._microphoneSource.disconnect();this._microphoneTag=b.toLowerCase();this._microphoneSource=this._audioContext.createMediaStreamSource(a);this._microphoneSource.connect(this.GetDestinationForTag(this._microphoneTag))}_OnGetOutputStream(){this._destMediaStreamNode||(this._destMediaStreamNode=this._audioContext.createMediaStreamDestination(),this._destinationNode.connect(this._destMediaStreamNode));return this._destMediaStreamNode.stream}static EqualsNoCase(a,b){return a.length!==b.length?!1:a===
b?!0:a.toLowerCase()===b.toLowerCase()}static ToDegrees(a){return a*e}static DbToLinearNoCap(a){return Math.pow(10,a/20)}static DbToLinear(a){return Math.max(Math.min(self.AudioDOMHandler.DbToLinearNoCap(a),1),0)}static LinearToDbNoCap(a){return Math.log(a)/Math.log(10)*20}static LinearToDb(a){return self.AudioDOMHandler.LinearToDbNoCap(Math.max(Math.min(a,1),0))}static e4(a,b){return 1-Math.exp(-b*a)}};self.RuntimeInterface.AddDOMHandlerClass(self.AudioDOMHandler)}"use strict";
self.C3AudioBuffer=class{constructor(e,a,b,c,h){this._audioDomHandler=e;this._originalUrl=a;this._url=b;this._type=c;this._isMusic=h;this._api="";this._loadState="not-loaded";this._loadPromise=null}Release(){this._loadState="not-loaded";this._loadPromise=this._audioDomHandler=null}static Create(e,a,b,c,h){const m="audio/webm; codecs=opus"===c&&!e.SupportsWebMOpus();h&&m&&e._SetHasAnySoftwareDecodedMusic();return!h||e.IsPlayMusicAsSound()||m?new self.C3WebAudioBuffer(e,a,b,c,h,m):new self.C3Html5AudioBuffer(e,
a,b,c,h)}CreateInstance(e){return"html5"===this._api?new self.C3Html5AudioInstance(this._audioDomHandler,this,e):new self.C3WebAudioInstance(this._audioDomHandler,this,e)}_Load(){}Load(){this._loadPromise||(this._loadPromise=this._Load());return this._loadPromise}IsLoaded(){}IsLoadedAndDecoded(){}HasFailedToLoad(){return"failed"===this._loadState}GetAudioContext(){return this._audioDomHandler.GetAudioContext()}GetApi(){return this._api}GetOriginalUrl(){return this._originalUrl}GetUrl(){return this._url}GetContentType(){return this._type}IsMusic(){return this._isMusic}GetDuration(){}};
"use strict";
self.C3Html5AudioBuffer=class extends self.C3AudioBuffer{constructor(e,a,b,c,h){super(e,a,b,c,h);this._api="html5";this._audioElem=new Audio;this._audioElem.crossOrigin="anonymous";this._audioElem.autoplay=!1;this._audioElem.preload="auto";this._loadReject=this._loadResolve=null;this._reachedCanPlayThrough=!1;this._audioElem.addEventListener("canplaythrough",()=>this._reachedCanPlayThrough=!0);this._outNode=this.GetAudioContext().createGain();this._mediaSourceNode=null;this._audioElem.addEventListener("canplay",()=>
{this._loadResolve&&(this._loadState="loaded",this._loadResolve(),this._loadReject=this._loadResolve=null);!this._mediaSourceNode&&this._audioElem&&(this._mediaSourceNode=this.GetAudioContext().createMediaElementSource(this._audioElem),this._mediaSourceNode.connect(this._outNode))});this.onended=null;this._audioElem.addEventListener("ended",()=>{if(this.onended)this.onended()});this._audioElem.addEventListener("error",m=>this._OnError(m))}Release(){this._audioDomHandler.ReleaseInstancesForBuffer(this);
this._outNode.disconnect();this._outNode=null;this._mediaSourceNode.disconnect();this._mediaSourceNode=null;this._audioElem&&!this._audioElem.paused&&this._audioElem.pause();this._audioElem=this.onended=null;super.Release()}_Load(){this._loadState="loading";return new Promise((e,a)=>{this._loadResolve=e;this._loadReject=a;this._audioElem.src=this._url})}_OnError(e){console.error(`[Construct 3] Audio '${this._url}' error: `,e);this._loadReject&&(this._loadState="failed",this._loadReject(e),this._loadReject=
this._loadResolve=null)}IsLoaded(){const e=4<=this._audioElem.readyState;e&&(this._reachedCanPlayThrough=!0);return e||this._reachedCanPlayThrough}IsLoadedAndDecoded(){return this.IsLoaded()}GetAudioElement(){return this._audioElem}GetOutputNode(){return this._outNode}GetDuration(){return this._audioElem.duration}};"use strict";
self.C3WebAudioBuffer=class extends self.C3AudioBuffer{constructor(e,a,b,c,h,m){super(e,a,b,c,h);this._api="webaudio";this._audioBuffer=this._audioData=null;this._needsSoftwareDecode=!!m}Release(){this._audioDomHandler.ReleaseInstancesForBuffer(this);this._audioBuffer=this._audioData=null;super.Release()}async _Fetch(){if(this._audioData)return this._audioData;var e=this._audioDomHandler.GetRuntimeInterface();if("cordova"===e.GetExportType()&&e.IsRelativeURL(this._url)&&e.IsFileProtocol())this._audioData=
await e.CordovaFetchLocalFileAsArrayBuffer(this._url);else{e=await fetch(this._url);if(!e.ok)throw Error(`error fetching audio data: ${e.status} ${e.statusText}`);this._audioData=await e.arrayBuffer()}}async _Decode(){if(this._audioBuffer)return this._audioBuffer;this._audioBuffer=await this._audioDomHandler.DecodeAudioData(this._audioData,this._needsSoftwareDecode);this._audioData=null}async _Load(){try{this._loadState="loading",await this._Fetch(),await this._Decode(),this._loadState="loaded"}catch(e){this._loadState=
"failed",console.error(`[Construct 3] Failed to load audio '${this._url}': `,e)}}IsLoaded(){return!(!this._audioData&&!this._audioBuffer)}IsLoadedAndDecoded(){return!!this._audioBuffer}GetAudioBuffer(){return this._audioBuffer}GetDuration(){return this._audioBuffer?this._audioBuffer.duration:0}};"use strict";
{let e=0;self.C3AudioInstance=class{constructor(a,b,c){this._audioDomHandler=a;this._buffer=b;this._tag=c;this._aiId=e++;this._gainNode=this.GetAudioContext().createGain();this._gainNode.connect(this.GetDestinationNode());this._pannerNode=null;this._isPannerEnabled=!1;this._pannerPosition=[0,0,0];this._pannerOrientation=[0,0,0];this._isStopped=!0;this._isLooping=this._resumeMe=this._isPaused=!1;this._volume=1;this._isMuted=!1;this._playbackRate=1;a=this._audioDomHandler.GetTimeScaleMode();this._isTimescaled=
1===a&&!this.IsMusic()||2===a;this._fadeEndTime=this._instUid=-1;this._stopOnFadeEnd=!1}Release(){this._buffer=this._audioDomHandler=null;this._pannerNode&&(this._pannerNode.disconnect(),this._pannerNode=null);this._gainNode.disconnect();this._gainNode=null}GetAudioContext(){return this._audioDomHandler.GetAudioContext()}GetDestinationNode(){return this._audioDomHandler.GetDestinationForTag(this._tag)}GetMasterVolume(){return this._audioDomHandler.GetMasterVolume()}GetCurrentTime(){return this._isTimescaled?
this._audioDomHandler.GetGameTime():performance.now()/1E3}GetOriginalUrl(){return this._buffer.GetOriginalUrl()}GetUrl(){return this._buffer.GetUrl()}GetContentType(){return this._buffer.GetContentType()}GetBuffer(){return this._buffer}IsMusic(){return this._buffer.IsMusic()}SetTag(a){this._tag=a}GetTag(){return this._tag}GetAiId(){return this._aiId}HasEnded(){}CanBeRecycled(){}IsPlaying(){return!this._isStopped&&!this._isPaused&&!this.HasEnded()}IsActive(){return!this._isStopped&&!this.HasEnded()}GetPlaybackTime(){}GetDuration(a){let b=
this._buffer.GetDuration();a&&(b/=this._playbackRate||.001);return b}Play(a,b,c,h){}Stop(){}Pause(){}IsPaused(){return this._isPaused}Resume(){}SetVolume(a){this._volume=a;this._gainNode.gain.cancelScheduledValues(0);this._fadeEndTime=-1;this._gainNode.gain.value=this.GetOverallVolume()}FadeVolume(a,b,c){if(!this.IsMuted()){a*=this.GetMasterVolume();var h=this._gainNode.gain;h.cancelScheduledValues(0);var m=this._audioDomHandler.GetAudioCurrentTime();b=m+b;h.setValueAtTime(h.value,m);h.linearRampToValueAtTime(a,
b);this._volume=a;this._fadeEndTime=b;this._stopOnFadeEnd=c}}_UpdateVolume(){this.SetVolume(this._volume)}Tick(a){-1!==this._fadeEndTime&&a>=this._fadeEndTime&&(this._fadeEndTime=-1,this._stopOnFadeEnd&&this.Stop(),this._audioDomHandler.PostTrigger("fade-ended",this._tag,this._aiId))}GetOverallVolume(){const a=this._volume*this.GetMasterVolume();return isFinite(a)?a:0}SetMuted(a){a=!!a;this._isMuted!==a&&(this._isMuted=a,this._UpdateMuted())}IsMuted(){return this._isMuted}IsSilent(){return this._audioDomHandler.IsSilent()}_UpdateMuted(){}SetLooping(a){}IsLooping(){return this._isLooping}SetPlaybackRate(a){this._playbackRate!==
a&&(this._playbackRate=a,this._UpdatePlaybackRate())}_UpdatePlaybackRate(){}GetPlaybackRate(){return this._playbackRate}Seek(a){}SetSuspended(a){}SetPannerEnabled(a){a=!!a;this._isPannerEnabled!==a&&((this._isPannerEnabled=a)?(this._pannerNode||(this._pannerNode=this.GetAudioContext().createPanner(),this._pannerNode.panningModel=this._audioDomHandler.GetPanningModel(),this._pannerNode.distanceModel=this._audioDomHandler.GetDistanceModel(),this._pannerNode.refDistance=this._audioDomHandler.GetReferenceDistance(),
this._pannerNode.maxDistance=this._audioDomHandler.GetMaxDistance(),this._pannerNode.rolloffFactor=this._audioDomHandler.GetRolloffFactor()),this._gainNode.disconnect(),this._gainNode.connect(this._pannerNode),this._pannerNode.connect(this.GetDestinationNode())):(this._pannerNode.disconnect(),this._gainNode.disconnect(),this._gainNode.connect(this.GetDestinationNode())))}SetPan(a,b,c,h,m,p){this._isPannerEnabled&&(this.SetPanXYA(a,b,c),a=self.AudioDOMHandler.ToDegrees,this._pannerNode.coneInnerAngle=
a(h),this._pannerNode.coneOuterAngle=a(m),this._pannerNode.coneOuterGain=p)}SetPanXYA(a,b,c){this._isPannerEnabled&&(this._pannerPosition[0]=a,this._pannerPosition[1]=b,this._pannerPosition[2]=0,this._pannerOrientation[0]=Math.cos(c),this._pannerOrientation[1]=Math.sin(c),this._pannerOrientation[2]=0,this._pannerNode.setPosition(...this._pannerPosition),this._pannerNode.setOrientation(...this._pannerOrientation))}SetUID(a){this._instUid=a}GetUID(){return this._instUid}GetResumePosition(){}Reconnect(a){const b=
this._pannerNode||this._gainNode;b.disconnect();b.connect(a)}GetState(){return{aiid:this.GetAiId(),tag:this._tag,duration:this.GetDuration(),volume:this._volume,isPlaying:this.IsPlaying(),playbackTime:this.GetPlaybackTime(),playbackRate:this.GetPlaybackRate(),uid:this._instUid,bufferOriginalUrl:this.GetOriginalUrl(),bufferUrl:"",bufferType:this.GetContentType(),isMusic:this.IsMusic(),isLooping:this.IsLooping(),isMuted:this.IsMuted(),resumePosition:this.GetResumePosition(),pan:this.GetPanState()}}_LoadAdditionalState(a){this.SetPlaybackRate(a.playbackRate);
this.SetMuted(a.isMuted)}GetPanState(){if(!this._pannerNode)return null;const a=this._pannerNode;return{pos:this._pannerPosition,orient:this._pannerOrientation,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this._instUid}}LoadPanState(a){if(a){this.SetPannerEnabled(!0);a=this._pannerNode;var b=a.pos;this._pannerPosition[0]=b[0];this._pannerPosition[1]=b[1];this._pannerPosition[2]=b[2];b=a.orient;this._pannerOrientation[0]=b[0];this._pannerOrientation[1]=b[1];this._pannerOrientation[2]=
b[2];a.setPosition(...this._pannerPosition);a.setOrientation(...this._pannerOrientation);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this._instUid=a.uid}else this.SetPannerEnabled(!1)}}}"use strict";
self.C3Html5AudioInstance=class extends self.C3AudioInstance{constructor(e,a,b){super(e,a,b);this._buffer.GetOutputNode().connect(this._gainNode);this._buffer.onended=()=>this._OnEnded()}Release(){this.Stop();this._buffer.GetOutputNode().disconnect();super.Release()}GetAudioElement(){return this._buffer.GetAudioElement()}_OnEnded(){this._isStopped=!0;this._instUid=-1;this._audioDomHandler.PostTrigger("ended",this._tag,this._aiId)}HasEnded(){return this.GetAudioElement().ended}CanBeRecycled(){return this._isStopped?
!0:this.HasEnded()}GetPlaybackTime(){let e=this.GetAudioElement().currentTime;this._isLooping||(e=Math.min(e,this.GetDuration()));return e}Play(e,a,b,c){c=this.GetAudioElement();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==e&&(c.loop=e);this.SetVolume(a);c.muted&&(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(h){console.warn(`[Construct 3] Exception seeking audio '${this._buffer.GetUrl()}' to position '${b}': `,h)}this._audioDomHandler.TryPlayMedia(c);this._isPaused=this._isStopped=
!1;this._isLooping=e;this._playbackRate=1}Stop(){const e=this.GetAudioElement();e.paused||e.pause();this._audioDomHandler.RemovePendingPlay(e);this._isStopped=!0;this._isPaused=!1;this._instUid=-1}Pause(){if(!(this._isPaused||this._isStopped||this.HasEnded())){var e=this.GetAudioElement();e.paused||e.pause();this._audioDomHandler.RemovePendingPlay(e);this._isPaused=!0}}Resume(){!this._isPaused||this._isStopped||this.HasEnded()||(this._audioDomHandler.TryPlayMedia(this.GetAudioElement()),this._isPaused=
!1)}_UpdateMuted(){this.GetAudioElement().muted=this._isMuted||this.IsSilent()}SetLooping(e){e=!!e;this._isLooping!==e&&(this._isLooping=e,this.GetAudioElement().loop=e)}_UpdatePlaybackRate(){let e=this._playbackRate;this._isTimescaled&&(e*=this._audioDomHandler.GetTimeScale());try{this.GetAudioElement().playbackRate=e}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${e}':`,a)}}Seek(e){if(!this._isStopped&&!this.HasEnded())try{this.GetAudioElement().currentTime=e}catch(a){console.warn(`[Construct 3] Error seeking audio to '${e}': `,
a)}}GetResumePosition(){return this.GetPlaybackTime()}SetSuspended(e){e?this.IsPlaying()?(this.GetAudioElement().pause(),this._resumeMe=!0):this._resumeMe=!1:this._resumeMe&&(this._audioDomHandler.TryPlayMedia(this.GetAudioElement()),this._resumeMe=!1)}};"use strict";
self.C3WebAudioInstance=class extends self.C3AudioInstance{constructor(e,a,b){super(e,a,b);this._bufferSource=null;this._onended_handler=c=>this._OnEnded(c);this._hasPlaybackEnded=!0;this._activeSource=null;this._resumePosition=this._playFromSeekPos=this._playStartTime=0;this._muteVol=1}Release(){this.Stop();this._ReleaseBufferSource();this._onended_handler=null;super.Release()}_ReleaseBufferSource(){this._bufferSource&&this._bufferSource.disconnect();this._activeSource=this._bufferSource=null}_OnEnded(e){this._isPaused||
this._resumeMe||e.target!==this._activeSource||(this._isStopped=this._hasPlaybackEnded=!0,this._instUid=-1,this._ReleaseBufferSource(),this._audioDomHandler.PostTrigger("ended",this._tag,this._aiId))}HasEnded(){return!this._isStopped&&this._bufferSource&&this._bufferSource.loop||this._isPaused?!1:this._hasPlaybackEnded}CanBeRecycled(){return!this._bufferSource||this._isStopped?!0:this.HasEnded()}GetPlaybackTime(){let e;e=this._isPaused?this._resumePosition:this._playFromSeekPos+(this.GetCurrentTime()-
this._playStartTime)*this._playbackRate;this._isLooping||(e=Math.min(e,this.GetDuration()));return e}Play(e,a,b,c){this._muteVol=1;this.SetVolume(a);this._ReleaseBufferSource();this._bufferSource=this.GetAudioContext().createBufferSource();this._bufferSource.buffer=this._buffer.GetAudioBuffer();this._bufferSource.connect(this._gainNode);this._activeSource=this._bufferSource;this._bufferSource.onended=this._onended_handler;this._bufferSource.loop=e;this._bufferSource.start(c,b);this._isPaused=this._isStopped=
this._hasPlaybackEnded=!1;this._isLooping=e;this._playbackRate=1;this._playStartTime=this.GetCurrentTime();this._playFromSeekPos=b}Stop(){if(this._bufferSource)try{this._bufferSource.stop(0)}catch(e){}this._isStopped=!0;this._isPaused=!1;this._instUid=-1}Pause(){this._isPaused||this._isStopped||this.HasEnded()||(this._resumePosition=this.GetPlaybackTime(),this._isLooping&&(this._resumePosition%=this.GetDuration()),this._isPaused=!0,this._bufferSource.stop(0))}Resume(){!this._isPaused||this._isStopped||
this.HasEnded()||(this._ReleaseBufferSource(),this._bufferSource=this.GetAudioContext().createBufferSource(),this._bufferSource.buffer=this._buffer.GetAudioBuffer(),this._bufferSource.connect(this._gainNode),this._activeSource=this._bufferSource,this._bufferSource.onended=this._onended_handler,this._bufferSource.loop=this._isLooping,this._UpdateVolume(),this._UpdatePlaybackRate(),this._bufferSource.start(0,this._resumePosition),this._playStartTime=this.GetCurrentTime(),this._playFromSeekPos=this._resumePosition,
this._isPaused=!1)}GetOverallVolume(){return super.GetOverallVolume()*this._muteVol}_UpdateMuted(){this._muteVol=this._isMuted||this.IsSilent()?0:1;this._UpdateVolume()}SetLooping(e){e=!!e;this._isLooping!==e&&(this._isLooping=e,this._bufferSource&&(this._bufferSource.loop=e))}_UpdatePlaybackRate(){let e=this._playbackRate;this._isTimescaled&&(e*=this._audioDomHandler.GetTimeScale());this._bufferSource&&(this._bufferSource.playbackRate.value=e)}Seek(e){this._isStopped||this.HasEnded()||(this._isPaused?
this._resumePosition=e:(this.Pause(),this._resumePosition=e,this.Resume()))}GetResumePosition(){return this._resumePosition}SetSuspended(e){e?this.IsPlaying()?(this._resumeMe=!0,this._resumePosition=this.GetPlaybackTime(),this._isLooping&&(this._resumePosition%=this.GetDuration()),this._bufferSource.stop(0)):this._resumeMe=!1:this._resumeMe&&(this._ReleaseBufferSource(),this._bufferSource=this.GetAudioContext().createBufferSource(),this._bufferSource.buffer=this._buffer.GetAudioBuffer(),this._bufferSource.connect(this._gainNode),
this._activeSource=this._bufferSource,this._bufferSource.onended=this._onended_handler,this._bufferSource.loop=this._isLooping,this._UpdateVolume(),this._UpdatePlaybackRate(),this._bufferSource.start(0,this._resumePosition),this._playStartTime=this.GetCurrentTime(),this._playFromSeekPos=this._resumePosition,this._resumeMe=!1)}_LoadAdditionalState(e){super._LoadAdditionalState(e);this._resumePosition=e.resumePosition}};"use strict";
{class e{constructor(a){this._audioDomHandler=a;this._audioContext=a.GetAudioContext();this._index=-1;this._type=this._tag="";this._params=null}Release(){this._audioContext=null}_SetIndex(a){this._index=a}GetIndex(){return this._index}_SetTag(a){this._tag=a}GetTag(){return this._tag}CreateGain(){return this._audioContext.createGain()}GetInputNode(){}ConnectTo(a){}SetAudioParam(a,b,c,h){a.cancelScheduledValues(0);if(0===h)a.value=b;else{var m=this._audioContext.currentTime;h+=m;switch(c){case 0:a.setValueAtTime(b,
h);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,h);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,h)}}}GetState(){return{type:this._type,tag:this._tag,params:this._params}}}self.C3AudioFilterFX=class extends e{constructor(a,b,c,h,m,p,u){super(a);this._type="filter";this._params=[b,c,h,m,p,u];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=u;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-u;this._filterNode=
this._audioContext.createBiquadFilter();this._filterNode.type=b;this._filterNode.frequency.value=c;this._filterNode.detune.value=h;this._filterNode.Q.value=m;this._filterNode.gain.vlaue=p;this._inputNode.connect(this._filterNode);this._inputNode.connect(this._dryNode);this._filterNode.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._filterNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();this._wetNode.connect(a);
this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[5]=b;this.SetAudioParam(this._wetNode.gain,b,c,h);this.SetAudioParam(this._dryNode.gain,1-b,c,h);break;case 1:this._params[1]=b;this.SetAudioParam(this._filterNode.frequency,b,c,h);break;case 2:this._params[2]=b;this.SetAudioParam(this._filterNode.detune,b,c,h);break;case 3:this._params[3]=b;this.SetAudioParam(this._filterNode.Q,
b,c,h);break;case 4:this._params[4]=b,this.SetAudioParam(this._filterNode.gain,b,c,h)}}};self.C3AudioDelayFX=class extends e{constructor(a,b,c,h){super(a);this._type="delay";this._params=[b,c,h];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=h;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-h;this._mainNode=this.CreateGain();this._delayNode=this._audioContext.createDelay(b);this._delayNode.delayTime.value=b;this._delayGainNode=this.CreateGain();
this._delayGainNode.gain.value=c;this._inputNode.connect(this._mainNode);this._inputNode.connect(this._dryNode);this._mainNode.connect(this._wetNode);this._mainNode.connect(this._delayNode);this._delayNode.connect(this._delayGainNode);this._delayGainNode.connect(this._mainNode)}Release(){this._inputNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();this._mainNode.disconnect();this._delayNode.disconnect();this._delayGainNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();
this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){const m=self.AudioDOMHandler.DbToLinear;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[2]=b;this.SetAudioParam(this._wetNode.gain,b,c,h);this.SetAudioParam(this._dryNode.gain,1-b,c,h);break;case 4:this._params[1]=m(b);this.SetAudioParam(this._delayGainNode.gain,m(b),c,h);break;case 5:this._params[0]=b,this.SetAudioParam(this._delayNode.delayTime,b,c,h)}}};
self.C3AudioConvolveFX=class extends e{constructor(a,b,c,h){super(a);this._type="convolution";this._params=[c,h];this._bufferType=this._bufferUrl=this._bufferOriginalUrl="";this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=h;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-h;this._convolveNode=this._audioContext.createConvolver();this._convolveNode.normalize=c;this._convolveNode.buffer=b;this._inputNode.connect(this._convolveNode);this._inputNode.connect(this._dryNode);
this._convolveNode.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._convolveNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this._params[1]=b,this.SetAudioParam(this._wetNode.gain,b,c,h),this.SetAudioParam(this._dryNode.gain,
1-b,c,h)}}_SetBufferInfo(a,b,c){this._bufferOriginalUrl=a;this._bufferUrl=b;this._bufferType=c}GetState(){const a=super.GetState();a.bufferOriginalUrl=this._bufferOriginalUrl;a.bufferUrl="";a.bufferType=this._bufferType;return a}};self.C3AudioFlangerFX=class extends e{constructor(a,b,c,h,m,p){super(a);this._type="flanger";this._params=[b,c,h,m,p];this._inputNode=this.CreateGain();this._dryNode=this.CreateGain();this._dryNode.gain.value=1-p/2;this._wetNode=this.CreateGain();this._wetNode.gain.value=
p/2;this._feedbackNode=this.CreateGain();this._feedbackNode.gain.value=m;this._delayNode=this._audioContext.createDelay(b+c);this._delayNode.delayTime.value=b;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=h;this._oscGainNode=this.CreateGain();this._oscGainNode.gain.value=c;this._inputNode.connect(this._delayNode);this._inputNode.connect(this._dryNode);this._delayNode.connect(this._wetNode);this._delayNode.connect(this._feedbackNode);this._feedbackNode.connect(this._delayNode);
this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._delayNode.delayTime);this._oscNode.start(0)}Release(){this._oscNode.stop(0);this._inputNode.disconnect();this._delayNode.disconnect();this._oscNode.disconnect();this._oscGainNode.disconnect();this._dryNode.disconnect();this._wetNode.disconnect();this._feedbackNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,
b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[4]=b;this.SetAudioParam(this._wetNode.gain,b/2,c,h);this.SetAudioParam(this._dryNode.gain,1-b/2,c,h);break;case 6:this._params[1]=b/1E3;this.SetAudioParam(this._oscGainNode.gain,b/1E3,c,h);break;case 7:this._params[2]=b;this.SetAudioParam(this._oscNode.frequency,b,c,h);break;case 8:this._params[3]=b/100,this.SetAudioParam(this._feedbackNode.gain,b/100,c,h)}}};self.C3AudioPhaserFX=class extends e{constructor(a,b,c,h,m,p,u){super(a);
this._type="phaser";this._params=[b,c,h,m,p,u];this._inputNode=this.CreateGain();this._dryNode=this.CreateGain();this._dryNode.gain.value=1-u/2;this._wetNode=this.CreateGain();this._wetNode.gain.value=u/2;this._filterNode=this._audioContext.createBiquadFilter();this._filterNode.type="allpass";this._filterNode.frequency.value=b;this._filterNode.detune.value=c;this._filterNode.Q.value=h;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=p;this._oscGainNode=this.CreateGain();
this._oscGainNode.gain.value=m;this._inputNode.connect(this._filterNode);this._inputNode.connect(this._dryNode);this._filterNode.connect(this._wetNode);this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._filterNode.frequency);this._oscNode.start(0)}Release(){this._oscNode.stop(0);this._inputNode.disconnect();this._filterNode.disconnect();this._oscNode.disconnect();this._oscGainNode.disconnect();this._dryNode.disconnect();this._wetNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();
this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[5]=b;this.SetAudioParam(this._wetNode.gain,b/2,c,h);this.SetAudioParam(this._dryNode.gain,1-b/2,c,h);break;case 1:this._params[0]=b;this.SetAudioParam(this._filterNode.frequency,b,c,h);break;case 2:this._params[1]=b;this.SetAudioParam(this._filterNode.detune,b,c,h);break;case 3:this._params[2]=b;this.SetAudioParam(this._filterNode.Q,
b,c,h);break;case 6:this._params[3]=b;this.SetAudioParam(this._oscGainNode.gain,b,c,h);break;case 7:this._params[4]=b,this.SetAudioParam(this._oscNode.frequency,b,c,h)}}};self.C3AudioGainFX=class extends e{constructor(a,b){super(a);this._type="gain";this._params=[b];this._node=this.CreateGain();this._node.gain.value=b}Release(){this._node.disconnect();super.Release()}ConnectTo(a){this._node.disconnect();this._node.connect(a)}GetInputNode(){return this._node}SetParam(a,b,c,h){const m=self.AudioDOMHandler.DbToLinear;
switch(a){case 4:this._params[0]=m(b),this.SetAudioParam(this._node.gain,m(b),c,h)}}};self.C3AudioTremoloFX=class extends e{constructor(a,b,c){super(a);this._type="tremolo";this._params=[b,c];this._node=this.CreateGain();this._node.gain.value=1-c/2;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=b;this._oscGainNode=this.CreateGain();this._oscGainNode.gain.value=c/2;this._oscNode.connect(this._oscGainNode);this._oscGainNode.connect(this._node.gain);this._oscNode.start(0)}Release(){this._oscNode.stop(0);
this._oscNode.disconnect();this._oscGainNode.disconnect();this._node.disconnect();super.Release()}ConnectTo(a){this._node.disconnect();this._node.connect(a)}GetInputNode(){return this._node}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[1]=b;this.SetAudioParam(this._node.gain,1-b/2,c,h);this.SetAudioParam(this._oscGainNode.gain,b/2,c,h);break;case 7:this._params[0]=b,this.SetAudioParam(this._oscNode.frequency,b,c,h)}}};self.C3AudioRingModFX=class extends e{constructor(a,
b,c){super(a);this._type="ringmod";this._params=[b,c];this._inputNode=this.CreateGain();this._wetNode=this.CreateGain();this._wetNode.gain.value=c;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-c;this._ringNode=this.CreateGain();this._ringNode.gain.value=0;this._oscNode=this._audioContext.createOscillator();this._oscNode.frequency.value=b;this._oscNode.connect(this._ringNode.gain);this._oscNode.start(0);this._inputNode.connect(this._ringNode);this._inputNode.connect(this._dryNode);this._ringNode.connect(this._wetNode)}Release(){this._oscNode.stop(0);
this._oscNode.disconnect();this._ringNode.disconnect();this._inputNode.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}ConnectTo(a){this._wetNode.disconnect();this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this._params[1]=b;this.SetAudioParam(this._wetNode.gain,b,c,h);this.SetAudioParam(this._dryNode.gain,1-b,c,h);break;case 7:this._params[0]=
b,this.SetAudioParam(this._oscNode.frequency,b,c,h)}}};self.C3AudioDistortionFX=class extends e{constructor(a,b,c,h,m,p){super(a);this._type="distortion";this._params=[b,c,h,m,p];this._inputNode=this.CreateGain();this._preGain=this.CreateGain();this._postGain=this.CreateGain();this._SetDrive(h,m);this._wetNode=this.CreateGain();this._wetNode.gain.value=p;this._dryNode=this.CreateGain();this._dryNode.gain.value=1-p;this._waveShaper=this._audioContext.createWaveShaper();this._curve=new Float32Array(65536);
this._GenerateColortouchCurve(b,c);this._waveShaper.curve=this._curve;this._inputNode.connect(this._preGain);this._inputNode.connect(this._dryNode);this._preGain.connect(this._waveShaper);this._waveShaper.connect(this._postGain);this._postGain.connect(this._wetNode)}Release(){this._inputNode.disconnect();this._preGain.disconnect();this._waveShaper.disconnect();this._postGain.disconnect();this._wetNode.disconnect();this._dryNode.disconnect();super.Release()}_SetDrive(a,b){.01>a&&(a=.01);this._preGain.gain.value=
a;this._postGain.gain.value=Math.pow(1/a,.6)*b}_GenerateColortouchCurve(a,b){for(let c=0;32768>c;++c){let h=c/32768;h=this._Shape(h,a,b);this._curve[32768+c]=h;this._curve[32768-c-1]=-h}}_Shape(a,b,c){c=1.05*c*b-b;const h=0>a?-1:1;a=0>a?-a:a;return(a<b?a:b+c*self.AudioDOMHandler.e4(a-b,1/c))*h}ConnectTo(a){this._wetNode.disconnect();this._wetNode.connect(a);this._dryNode.disconnect();this._dryNode.connect(a)}GetInputNode(){return this._inputNode}SetParam(a,b,c,h){switch(a){case 0:b=Math.max(Math.min(b/
100,1),0),this._params[4]=b,this.SetAudioParam(this._wetNode.gain,b,c,h),this.SetAudioParam(this._dryNode.gain,1-b,c,h)}}};self.C3AudioCompressorFX=class extends e{constructor(a,b,c,h,m,p){super(a);this._type="compressor";this._params=[b,c,h,m,p];this._node=this._audioContext.createDynamicsCompressor();this._node.threshold.value=b;this._node.knee.value=c;this._node.ratio.value=h;this._node.attack.value=m;this._node.release.value=p}Release(){this._node.disconnect();super.Release()}ConnectTo(a){this._node.disconnect();
this._node.connect(a)}GetInputNode(){return this._node}SetParam(a,b,c,h){}};self.C3AudioAnalyserFX=class extends e{constructor(a,b,c){super(a);this._type="analyser";this._params=[b,c];this._node=this._audioContext.createAnalyser();this._node.fftSize=b;this._node.smoothingTimeConstant=c;this._freqBins=new Float32Array(this._node.frequencyBinCount);this._signal=new Uint8Array(b);this._rms=this._peak=0;this._audioDomHandler._AddAnalyser(this)}Release(){this._audioDomHandler._RemoveAnalyser(this);this._node.disconnect();
super.Release()}Tick(){this._node.getFloatFrequencyData(this._freqBins);this._node.getByteTimeDomainData(this._signal);const a=this._node.fftSize;let b=this._peak=0;for(var c=0;c<a;++c){let h=(this._signal[c]-128)/128;0>h&&(h=-h);this._peak<h&&(this._peak=h);b+=h*h}c=self.AudioDOMHandler.LinearToDb;this._peak=c(this._peak);this._rms=c(Math.sqrt(b/a))}ConnectTo(a){this._node.disconnect();this._node.connect(a)}GetInputNode(){return this._node}SetParam(a,b,c,h){}GetData(){return{tag:this.GetTag(),index:this.GetIndex(),
peak:this._peak,rms:this._rms,binCount:this._node.frequencyBinCount,freqBins:this._freqBins}}}}"use strict";
{function e(a){a.stopPropagation()}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"button")}CreateElement(a,b){const c=document.createElement("input");var h=c;b.isCheckbox?(c.type="checkbox",h=document.createElement("label"),h.appendChild(c),h.appendChild(document.createTextNode("")),h.style.fontFamily="sans-serif",h.style.userSelect="none",h.style.webkitUserSelect="none",h.style.display="inline-block",h.style.color="black"):c.type="button";h.style.position=
"absolute";h.addEventListener("touchstart",e);h.addEventListener("touchmove",e);h.addEventListener("touchend",e);h.addEventListener("mousedown",e);h.addEventListener("mouseup",e);h.addEventListener("keydown",e);h.addEventListener("keyup",e);c.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);this.UpdateState(h,b);return h}_GetInputElem(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}_GetFocusElement(a){return this._GetInputElem(a)}UpdateState(a,
b){const c=this._GetInputElem(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:a.lastChild.textContent=b.text}})}"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(e){super(e,"touch");this.AddRuntimeMessageHandler("request-permission",a=>this._OnRequestPermission(a))}async _OnRequestPermission(e){e=e.type;let a=!0;0===e?a=await this._RequestOrientationPermission():1===e&&(a=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:e,result:a})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request orientation permission: ",e),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(e){return console.warn("[Touch] Failed to request motion permission: ",e),!1}}});"use strict";
{function e(a){return a&&!a.paused&&!a.ended&&0<a.currentTime}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(a){super(a,"video");this.SetAutoAttach(!1);this._supportsRvfc=this._isRuntimeInWorker=!1;this._numVideos=this._sequenceNumber=0;this._destroyedVideos=new WeakSet;this.AddRuntimeMessageHandler("init",b=>this._OnInit(b));this.AddDOMElementMessageHandler("play",b=>this._OnPlay(b));this.AddDOMElementMessageHandler("pause",b=>this._OnPause(b));this.AddDOMElementMessageHandler("set-source",
(b,c)=>this._OnSetSource(b,c));this.AddDOMElementMessageHandler("set-playback-time",(b,c)=>this._OnSetPlaybackTime(b,c));this.AddDOMElementMessageHandler("set-looping",(b,c)=>this._OnSetLooping(b,c));this.AddDOMElementMessageHandler("set-muted",(b,c)=>this._OnSetMuted(b,c));this.AddDOMElementMessageHandler("set-volume",(b,c)=>this._OnSetVolume(b,c));self.C3Video_GetElement=b=>this.GetElementById(b)}async _OnInit(a){this._isRuntimeInWorker=a.isInWorker;a=document.createElement("video");this._supportsRvfc=
!!a.requestVideoFrameCallback;return{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}TryPlayMedia(a){this._iRuntime.TryPlayMedia(a);this._isRuntimeInWorker&&this._supportsRvfc&&-1===a.c3_rvfcId&&(a.c3_rvfcId=a.requestVideoFrameCallback(()=>this._OnVideoFrameCallback(a)))}RemovePendingPlay(a){this._iRuntime.RemovePendingPlay(a);this._isRuntimeInWorker&&this._supportsRvfc&&-1!==a.c3_rvfcId&&(a.cancelVideoFrameCallback(a.c3_rvfcId),
a.c3_rvfcId=-1)}async _OnVideoFrameCallback(a){if(!this._destroyedVideos.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>this._OnVideoFrameCallback(a));try{const b=a.c3_sequenceNumber++,c=await createImageBitmap(a);b>a.c3_lastFrameSequence&&(a.c3_imageBitmap=c,a.c3_lastFrameSequence=b)}catch(b){}}}CreateElement(a,b){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",
()=>this._SendPlaybackEvent(c,a,0));c.addEventListener("canplaythrough",()=>this._SendPlaybackEvent(c,a,1));c.addEventListener("ended",()=>this._SendPlaybackEvent(c,a,2));c.addEventListener("error",()=>this._SendPlaybackEvent(c,a,3));c.addEventListener("loadstart",()=>this._SendPlaybackEvent(c,a,4));c.addEventListener("playing",()=>this._SendPlaybackEvent(c,a,5));c.addEventListener("pause",()=>this._SendPlaybackEvent(c,a,6));c.addEventListener("stalled",()=>this._SendPlaybackEvent(c,a,7));const h=
b.autoplay;0===h?(c.autoplay=!1,c.preload="none"):1===h?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;b.src&&(c.src=b.src);2===h&&this.TryPlayMedia(c);this._numVideos++;this._StartTicking();return c}_SendPlaybackEvent(a,b,c){this._destroyedVideos.has(a)||this.PostToRuntimeElement("playback-event",b,{type:c})}UpdateState(a,b){}DestroyElement(a){this.RemovePendingPlay(a);e(a)&&a.pause();a.src="";this._numVideos=Math.max(this._numVideos-1,0);0===this._numVideos&&this._StopTicking();this._destroyedVideos.add(a)}_OnPlay(a){this.TryPlayMedia(a)}_OnPause(a){this.RemovePendingPlay(a);
a.pause()}_OnSetSource(a,b){a.src=b.src;a.load()}_OnSetPlaybackTime(a,b){try{a.currentTime=b.time}catch(c){console.error("[Video] Exception setting playback time: ",c)}}_OnSetLooping(a,b){a.loop=b.isLooping}_OnSetMuted(a,b){a.muted=b.isMuted}_OnSetVolume(a,b){a.volume=b.volume}Tick(){const a={},b={sequenceNumber:this._sequenceNumber++,videoData:a},c=[],h=[];for(const [m,p]of this._elementMap.entries()){const u={currentTime:p.currentTime,duration:p.duration,videoWidth:p.videoWidth,videoHeight:p.videoHeight};
if(this._isRuntimeInWorker)if(this._supportsRvfc){const v=p.c3_imageBitmap;p.c3_imageBitmap=null;(u.imageBitmap=v)&&c.push(v)}else h.push(createImageBitmap(p).then(v=>{u.imageBitmap=v;c.push(v)}).catch(v=>{u.imageBitmap=null}));a[m.toString()]=u}Promise.all(h).then(()=>this.PostToRuntime("state",b,!1,c))}})};
